version: '3'

tasks:
  dev:
    cmds:
      - npm run start:dev
    env:
      NODE_ENV: 'development'
  build:
    cmds:
      - npm run build
  prod:
    cmds:
      - npm run start:prod
    env:
      NODE_ENV: 'production'
  install: npm install
  test:
    cmds:
      - npm run test
  clean:
    cmds:
      - rm -rf ./husky
      - rm -rf ./node_modules
      - rm -rf ./dist
  gen-secret:
    cmds:
      - npx @better-auth/cli secret
