export const BEFORE_HOOK_KEY = Symbol('BEFORE_HOOK');
export const AFTER_HOOK_KEY = Symbol('AFTER_HOOK');
export const HOOK_KEY = Symbol('HOOK');
export const AUTH_INSTANCE_KEY = Symbol('AUTH_INSTANCE');
export const AUTH_MODULE_OPTIONS_KEY = Symbol('AUTH_MODULE_OPTIONS');
export const AUTH_IGNORE_ROUTERS = ['messages'];
export const ROLE_METADATA_KEY = Symbol('ROLE_METADATA_KEY');
export const DEFAULT_PORT = 3000;
export const API_GLOBAL_PREFIX = 'api';
export const APP_NAME = 'Anex';
export const DEFAULT_ADMIN_ID = '019c28c6-ae97-7684-97ad-8b2895af15cf';
export const WORKER_TIMEOUT = 60000; // milliseconds
export const API_KEY_LENGTH = 36;
